stages:
  - dev
  - stage
  - prod

deploy_dev:
  stage: dev
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh root@1.1.1.1 -p22 -o "StrictHostKeyChecking=no" -tt "cd /var/www/projects/shopify-app/qr-code && git pull origin master && sh rebuild.sh $SHOPIFY_API_KEY $SHOPIFY_API_SECRET $SHOPIFY_HOST"
